### ISSUE TITLE
Navigation Bar Design

### ISSUE THREAD

**Issue by littlepotato123** [littlepotato123/Project-Share#15]
There are a few design aspects of the Navigation Bar that I think need some fixing: 
- Title: I think the title "Project Sh@are" shouldn't be underlined and also we should probably remove the extra "a" after @.
- Search Bar: I already added an issue for the search bar and the button and to see it you can go https://github.com/littlepotato123/Project-Share/issues/14 . 
- NavLink Placement: Also I think, without signing in, we could try to move the navigation links although way to the right of the navigation bar instead of a little to the left of the search bar. 
- NavLink Placement when Logged In: I think what we can do when someone is logged in, is instead of listing 4 more links and buttons, we could have a little drop down. The navigation bar would only show the regular links and the username of the user, and if someone clicked on the username, it would show a drop down. This is what the drop down might look like: 
     - (Username)
         - Link to Author Page
         - Create new post
         - Logout Button

**Comment by akshatarora10** [comment]
there is no extra "a" after "@"

**Comment by akshatarora10** [comment]
The nav links are already to the right, sorry, but I don't think I understand your concern properly

**Comment by akshatarora10** [comment]
I MADE THE DROPDOWN!!!!
YESSIRR!!! 
FEELSSS SO GOOD TO FIGURE IT OUT!!! 
But i need help displaying it, like putting the file into the navigation, for me it's not working

**Comment by littlepotato123** [comment]
Just finished the basic navigation but there is still styling issues. We need to change up the inputs, buttons, and the title. Also, the color scheme needs to be fixed, but the positions, font-size and the drop-down is working. The navigation isn't completed, but most of the functionality is done!

**Comment by littlepotato123** [comment]
Added toggle to switch between searching by category and author.
