### ISSUE TITLE
Post Content

### ISSUE THREAD

**Issue by littlepotato123** [littlepotato123/Project-Share#18]
- Comments: Load 3 Comments at a time and have a load more button that will continuously load more comments when you click it.
     - Add a comment body and add a design similar to a post
- Category: Add a category link to the post's category
- Spacing Between Like Button and No. of Likes
- Make Comments Button more visible as a button and not just as regular text
- Add a smaller loading bar for the comments

**Comment by akshatarora10** [comment]
1) My comments are not loading even when I am signed up
2) When I wasn't signed up and/or logged in, I was still able to like a post
3) When someone comments, it should give them an alert telling them that their comment was posted if they are logged in, if not, then it should let the user know their comment is not posted

**Comment by akshatarora10** [comment]
When I like a post, then I go to another tab(ex: trending) , and then I come back to the home page, it lets me add another like to the post.

**Comment by littlepotato123** [comment]
You should be able to like a post without being logged in, it doesn't check for authentication!

**Comment by littlepotato123** [comment]
Just finished!
