### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by littlepotato123** [littlepotato123/Project-Share#19]
- Both 
     - Both pages need a better alert to indicate to the user that there has been an error while logging in and if the email or password is wrong
     - Once done with signing up or logging in, the page should take them to the home page or alert them with an error
- Sign Up
    - Don't let the user sign up if they don't have a picture or at least confirm them that there is no picture selected because some people might not want to post a picture. 
    - If any fields are missing or empty, do not let the user reach the backend and alert them.

**Comment by akshatarora10** [comment]
I have an issue, for me, if I try to sign up without having a picture, it will not let me.
