### ISSUE TITLE
Comments 

### ISSUE THREAD

**Issue by akshatarora10** [littlepotato123/Project-Share#7]
1) When I click enter on my keyboard my comment does not get uploaded and it stays in the input box
2) When I actually add a comment it still doesn't add my comment

Btw, I tried this like 50 times, no idea why this isn't working.

**Comment by littlepotato123** [comment]
Okay, Thanks for letting me know, I will start fixing this issue as soon as possible!

**Comment by littlepotato123** [comment]
I just added a feature with the comments so that when you click enter, you will post the comment. Also, I could not figure out a way to actually load the comment into the array at live time, so now whenever you comment a post, it force reloads, which just automatically updates the comment array.
