### ISSUE TITLE
User account additions

### ISSUE THREAD

**Issue by akshatarora10** [littlepotato123/Project-Share#76]
Add link for the following: 
- Posts (auto-scroll down)
- Supporters (new page containing a list of supporters)
- Supporting (new page containing a list of everyone the user is supporting)

**Comment by littlepotato123** [comment]
**Added**
- Supported and Supporting Page
- Post Count

**Revision**
I think that the posts auto scroll will need some revision since when finished styling, the posts that load will automatically be on the first view, so we don't need an auto-scroll.
