### ISSUE TITLE
Cool features additions 

### ISSUE THREAD

**Issue by akshatarora10** [littlepotato123/Project-Share#77]
1. Add a functionality to submit for apple as well, Ctrl + Shift only works for windows

**Comment by littlepotato123** [comment]
I can add this feature since I have access to a mac, so I can quickly test this feature. It is an easy addition since we have added a function in the Tools.js that we can easily add an or statement to the CONTROL keybind check!

**Comment by littlepotato123** [comment]
Added Mac OS functionality, I just added an "or statement" to the check if the previous key was "Meta" because I did a little testing on a Mac, and when I console.log(e.key), when I clicked "Command" it logged "Meta", so I am assuming that is just part of the Mac OS.
